version: '2'
services:
  shadowsocks-server:
    image: aliessam/shadowsocks-server
    container_name: shadowsocks-server
    ports:
     - "8388:8388"
    restart: always
    volumes:
     - ./conf:/shadowsocks/conf
